/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import TestSceneLogic from "./scene/TestSceneLogic"
import MapScrollView from "./helper/MapScrollView"
import ResidentLogic from "./resident/ResidentLogic"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scene/TestSceneLogic.js",TestSceneLogic);
		reg("helper/MapScrollView.js",MapScrollView);
		reg("resident/ResidentLogic.js",ResidentLogic);
    }
}
GameConfig.width = 1336;
GameConfig.height = 750;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "scene/TestScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
