export default class GameEvent{
}

// 建造家园完成
GameEvent.CREATE_HOME_FINISH = "CREATE_HOME_FINISH";
// 建造医院完成
GameEvent.CREATE_HOSPITAL_FINISH = "CREATE_HOSPITAL_FINISH";
// 建造学校完成
GameEvent.CREATE_SCHOOL_FINISH = "CREATE_SCHOOL_FINISH";
// 建造幼儿园完成
GameEvent.CREATE_CHILDSCHOOL_FINISH = "CREATE_CHILDSCHOOL_FINISH";
// 建造发电厂完成
GameEvent.CREATE_POWERPLANT_FINISH = "CREATE_POWERPLANT_FINISH";
// 建造商店完成
GameEvent.CREATE_SHOP_FINISH = "CREATE_SHOP_FINISH";
// 建造农田完成
GameEvent.CREATE_FARMLAND_FINISH = "CREATE_FARMLAND_FINISH";
// 建造牧场完成
GameEvent.CREATE_PASTURE_FINISH = "CREATE_PASTURE_FINISH";
// 建造歌剧院完成
GameEvent.CREATE_OPERA_FINISH = "CREATE_OPERA_FINISH";
// 建造写字楼完成
GameEvent.CREATE_OFFICE_FINISH = "CREATE_OFFICE_FINISH";
// 建造警察局完成
GameEvent.CREATE_POLICESTATION_FINISH = "CREATE_POLICESTATION_FINISH";
// 建造科学实验室完成
GameEvent.CREATE_LAB_FINISH = "CREATE_LAB_FINISH";


// 打猎完成
GameEvent.HUNT_FINISH = "HUNT_FINISH";
// 生病
GameEvent.RESIDENT_SICK = "RESIDENT_SICK";
// 死亡
GameEvent.RESIDENT_DIE = "RESIDENT_DIE";
// 长大
GameEvent.RESIDENT_GROWUP = "RESIDENT_GROWUP";
